import type { Config } from "tailwindcss";

// Tokens ported verbatim from the Stitch design system
// (stitch_hostello_roommate_matcher/hostello_design_system/DESIGN.md).
// The prototype HTML uses these exact names, so converting screens is mechanical.
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        surface: "#f7fafc",
        "surface-dim": "#d7dadc",
        "surface-bright": "#f7fafc",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f1f4f6",
        "surface-container": "#ebeef0",
        "surface-container-high": "#e5e9eb",
        "surface-container-highest": "#e0e3e5",
        "on-surface": "#181c1e",
        "on-surface-variant": "#41474e",
        "inverse-surface": "#2d3133",
        "inverse-on-surface": "#eef1f3",
        outline: "#72787f",
        "outline-variant": "#c1c7cf",
        "surface-tint": "#2f6388",
        primary: "#003b5a",
        "on-primary": "#ffffff",
        "primary-container": "#1a5276",
        "on-primary-container": "#94c5ee",
        "inverse-primary": "#9bccf6",
        secondary: "#ac3509",
        "on-secondary": "#ffffff",
        "secondary-container": "#fe6f42",
        "on-secondary-container": "#631800",
        tertiary: "#003f3a",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#005852",
        "on-tertiary-container": "#69d0c6",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#cbe6ff",
        "primary-fixed-dim": "#9bccf6",
        "on-primary-fixed": "#001e30",
        "on-primary-fixed-variant": "#0e4b6e",
        "secondary-fixed": "#ffdbd0",
        "secondary-fixed-dim": "#ffb59f",
        "on-secondary-fixed": "#3a0a00",
        "on-secondary-fixed-variant": "#852300",
        "tertiary-fixed": "#8ef4e9",
        "tertiary-fixed-dim": "#71d7cd",
        "on-tertiary-fixed": "#00201d",
        "on-tertiary-fixed-variant": "#00504a",
        background: "#f7fafc",
        "on-background": "#181c1e",
        "surface-variant": "#e0e3e5",
      },
      fontFamily: {
        heading: ["Plus Jakarta Sans", "sans-serif"],
        body: ["Inter", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "1.3", fontWeight: "700" }],
        "headline-lg-mobile": ["24px", { lineHeight: "1.3", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "1.4", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "1.2", letterSpacing: "0.01em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "1.2", fontWeight: "500" }],
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        sm: "0.25rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      spacing: {
        base: "8px",
        gutter: "24px",
        "stack-sm": "12px",
        "stack-md": "24px",
        "stack-lg": "48px",
        "margin-mobile": "20px",
        "margin-desktop": "64px",
        "container-max": "1200px",
      },
      maxWidth: {
        "container-max": "1200px",
      },
      boxShadow: {
        card: "0px 4px 20px rgba(26, 82, 118, 0.05)",
        "card-hover": "0px 12px 32px rgba(26, 82, 118, 0.12)",
        "nav-up": "0px -4px 20px rgba(26, 82, 118, 0.05)",
      },
    },
  },
  plugins: [],
} satisfies Config;
