// Auto-generated: Material Symbols icon name -> codepoint for the subset font.
// Regenerate when adding icons. Rendering by codepoint keeps the bundled
// font tiny and lets TS reject unknown icons at compile time.
export const GLYPHS = {
  "add": 0xE145,
  "add_business": 0xE729,
  "add_photo_alternate": 0xE43E,
  "apartment": 0xEA40,
  "arrow_back": 0xE5C4,
  "arrow_forward": 0xE5C8,
  "bed": 0xEFDF,
  "block": 0xE033,
  "cake": 0xE7E9,
  "cancel": 0xE5C9,
  "celebration": 0xEA65,
  "check_circle": 0xE86C,
  "construction": 0xEA3C,
  "dashboard": 0xE871,
  "diversity_3": 0xF8D9,
  "edit": 0xE150,
  "error": 0xE000,
  "favorite": 0xE87D,
  "group": 0xE7EF,
  "handshake": 0xEBCB,
  "hourglass_top": 0xEA5B,
  "inbox": 0xE156,
  "local_bar": 0xE540,
  "logout": 0xE9BA,
  "meeting_room": 0xEB4F,
  "person_search": 0xF106,
  "place": 0xE0C8,
  "progress_activity": 0xE9D0,
  "receipt_long": 0xEF6E,
  "restaurant": 0xE56C,
  "schedule": 0xE192,
  "school": 0xE80C,
  "search": 0xE8B6,
  "search_off": 0xEA76,
  "single_bed": 0xEA48,
  "smoking_rooms": 0xEB4B,
  "upload_file": 0xE9FC,
  "verified": 0xE031,
  "verified_user": 0xE8E8,
  "wc": 0xE63D,
} as const;

export type IconName = keyof typeof GLYPHS;
